version: '3.8'

services:
  redis-node-1:
    image: redis:7-alpine
    container_name: redis-node-1
    ports:
      - "9000:9000"
    volumes:
      - redis-node-1-data:/data
      - ./config/redis-node-1.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
    networks:
      - redis-cluster-net
    healthcheck:
      test: ["CMD", "redis-cli", "-p", "9000", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M

  redis-node-2:
    image: redis:7-alpine
    container_name: redis-node-2
    ports:
      - "9001:9001"
    volumes:
      - redis-node-2-data:/data
      - ./config/redis-node-2.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
    networks:
      - redis-cluster-net
    healthcheck:
      test: ["CMD", "redis-cli", "-p", "9001", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M

  redis-node-3:
    image: redis:7-alpine
    container_name: redis-node-3
    ports:
      - "9002:9002"
    volumes:
      - redis-node-3-data:/data
      - ./config/redis-node-3.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
    networks:
      - redis-cluster-net
    healthcheck:
      test: ["CMD", "redis-cli", "-p", "9002", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M

  redis-node-4:
    image: redis:7-alpine
    container_name: redis-node-4
    ports:
      - "9003:9003"
    volumes:
      - redis-node-4-data:/data
      - ./config/redis-node-4.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
    networks:
      - redis-cluster-net
    healthcheck:
      test: ["CMD", "redis-cli", "-p", "9003", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M

  redis-node-5:
    image: redis:7-alpine
    container_name: redis-node-5
    ports:
      - "9004:9004"
    volumes:
      - redis-node-5-data:/data
      - ./config/redis-node-5.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
    networks:
      - redis-cluster-net
    healthcheck:
      test: ["CMD", "redis-cli", "-p", "9004", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M

  redis-node-6:
    image: redis:7-alpine
    container_name: redis-node-6
    ports:
      - "9005:9005"
    volumes:
      - redis-node-6-data:/data
      - ./config/redis-node-6.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
    networks:
      - redis-cluster-net
    healthcheck:
      test: ["CMD", "redis-cli", "-p", "9005", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M

networks:
  redis-cluster-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.21.0.0/16

volumes:
  redis-node-1-data:
  redis-node-2-data:
  redis-node-3-data:
  redis-node-4-data:
  redis-node-5-data:
  redis-node-6-data: