version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: redis-lab2
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes --loglevel debug
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  redis-insight:
    image: redislabs/redisinsight:latest
    container_name: redis-insight-lab2
    ports:
      - "8001:8001"
    volumes:
      - insight-data:/db
    depends_on:
      - redis

volumes:
  redis-data:
  insight-data:
